networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - gateway: 192.168.56.1
        subnet: 192.168.56.0/24
      driver: default
services:
  node0:
    build: .
    environment:
      ALGORITHM: echo
      EMPTY: null
      LOCATION: cs4545
      PID: 0
      TOPOLOGY: topologies/echo.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.56.10
    ports:
    - 9090:9090
    volumes:
    - ./output:/home/python/output
  node1:
    build: .
    environment:
      ALGORITHM: echo
      EMPTY: null
      LOCATION: cs4545
      PID: 1
      TOPOLOGY: topologies/echo.yaml
    networks:
      vpcbr:
        ipv4_address: 192.168.56.11
    ports:
    - 9091:9091
    volumes:
    - ./output:/home/python/output
version: '3.7'
x-common-variables:
  EMPTY: null
  TOPOLOGY: topologies/echo.yaml
